# This is a basic workflow to help you get started with Actions

name: Update README2

# Controls when the workflow will run
on:
  # AGENDAR EL TIEMPO 
  schedule:
    - cron: '* */12 * * *'
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Update Profile README

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
      - uses: raquelavila86/checkout@v4 git@github.com:raquelavila86/raquelavila86.git
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
